server:
  port: 3003

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/parking_db
    username: parking_user
    password: parking_pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        globally_quoted_identifiers: false
  task:
    execution:
      pool:
        core-size: 2
        max-size: 4
      thread-name-prefix: async-

logging:
  level:
    com.estapar.parking: DEBUG
    com.estapar.parking.service.EventQueueService: DEBUG

simulator:
  url: http://localhost:8080
